FROM node:latest as build

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

# COPY package.*json ./



# RUN npm install react-scripts -g --force 

EXPOSE 3000 3001
COPY . ./
RUN npm install --force --save
RUN mkdir -p node_modules/.cache && chmod -R 777 node_modules/.cache
RUN npm install axios --save
CMD ["npm", "start"]