
services:
  frontend:
    container_name: dss-site
    build:
      context: . 
      dockerfile: dockerfile.dev
    volumes:
    - '.:/app'
    - '/app/node_modules'
    ports:
      - 3000:3000
    stdin_open: true
  api:
    container_name: dss_api
    build:
      context: ./server
      dockerfile: dockerfile.dev
    volumes:
      - './server:/app'
    ports:
      - 5000:5000
    depends_on:
      - model
  model:
    container_name: dss_model
    build:
      context: ./model
      dockerfile: dockerfile
    volumes:
      - './model:/app'
    ports:
      - 8500:8500
      - 8501:8501