
services:
  frontend:
    container_name: dss-site
    build:
      context: . 
      dockerfile: dockerfile.dev
    volumes:
    - '.:/app'
    - '/app/node_modules'
    ports:
      - 3000:3000
  api:
    container_name: dss_api
    build:
      context: ./server
      dockerfile: dockerfile.dev
    volumes:
      - './server:/app'
    ports:
      - 5000:5000